// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd1t8QLjgyS2XXhuyWuLGLXRKK3HSLgVk',
    appId: '1:988122638107:web:a3cb8acbc620df777855be',
    messagingSenderId: '988122638107',
    projectId: 'automafarm',
    authDomain: 'automafarm.firebaseapp.com',
    storageBucket: 'automafarm.appspot.com',
    measurementId: 'G-92NBYKKZF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUOLebmIhl4_7-xHmLub-HW1PKdSl_XKk',
    appId: '1:988122638107:android:f3ba60c41c0946a07855be',
    messagingSenderId: '988122638107',
    projectId: 'automafarm',
    storageBucket: 'automafarm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSPXdhHgdI9QYP55wVBsyDeZZKAvqJwwU',
    appId: '1:988122638107:ios:b0725abd0438d4ab7855be',
    messagingSenderId: '988122638107',
    projectId: 'automafarm',
    storageBucket: 'automafarm.appspot.com',
    iosClientId: '988122638107-9eqh0g8esjjrm6ilvtk8t1ov4331cr6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.autofarm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSPXdhHgdI9QYP55wVBsyDeZZKAvqJwwU',
    appId: '1:988122638107:ios:86b43601ba9a54d37855be',
    messagingSenderId: '988122638107',
    projectId: 'automafarm',
    storageBucket: 'automafarm.appspot.com',
    iosClientId: '988122638107-2c4ff59uqf51na8gsa8ph4hh72qmu9nl.apps.googleusercontent.com',
    iosBundleId: 'com.example.autofarm.RunnerTests',
  );
}
